# This is the main configuration file for your Jekyll site.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# YAML Syntax:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Onboarding Kit
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Onboarding Kit for GitHub
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pjrellum.github.io/devfactors.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-toc

sidebar_folder:
- 01-repo-mgnt
- 02-collab-tools
- 03-dev-flow
- 04-sec-feat
- 05-github-tools
- 06-branching-strategy

just_the_docs:
  color_scheme: dark
  theme:
    default: dark
    toggle: true
  show_sidebar: true
  generate_sidebar: false
  navigation:
    - title: "Repository Management"
      url: "/01-repo-mgnt/"
    - title: "Collaboration Tools"
      url: "/02-collab-tools/"
    - title: "Development Flow"
      url: "/03-dev-flow/"
    - title: "Security Features"
      url: "/04-sec-feat/"
    - title: "GitHub Tools"
      url: "/05-github-tools/"
    - title: "Branching Strategy"
      url: "/06-branching-strategy/"
